name: Build and publish Testcontainers package

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'src/Testcontainers.Topaz/**'

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Pack NuGet package
      run: dotnet pack ./src/Testcontainers.Topaz/Testcontainers.Topaz.csproj -c Release --include-symbols -o ./publish
    - name: NuGet login
      uses: NuGet/login@v1
      id: login
      with:
        user: ${{ secrets.NUGET_USER }}
    - name: Push NuGet package
      run: dotnet nuget push "./publish/*.nupkg" --api-key ${{ steps.login.outputs.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
